services:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        restart: always
        env_file: .env
        ports:
            - ":3306"
        volumes:
            - /home/sclam/data/db_data:/var/lib/mysql
        networks:
            - back
    nginx:
        build: requirements/nginx
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - /home/sclam/data/wordpress_data:/var/www
        depends_on:
            - wordpress
        networks:
            - front
    wordpress:
        build: requirements/wordpress
        container_name: wordpress
        restart: always
        env_file: .env
        ports:
            - ":9000"
        volumes:
            - /home/sclam/data/wordpress_data:/var/www
        networks:
            - front
            - back
        depends_on:
            - mariadb
networks:
    front:
        driver: bridge
    back:
        driver: bridge